[profile.default]
src = 'src/contracts'
out = 'out'
test = 'src/contracts/foundry-test'
cache_path = 'forge-cache'
libs = ["node_modules", "lib"]
remappings = [
    '@aave/=node_modules/@aave/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config